import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat,Fraunces,Figtree } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const MontserratFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const FrauncesFont = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});
const FigtreeFont=Figtree({
  variable:"--font-figtree",
  subsets:["latin"]
});

export const metadata: Metadata = {
  title: "Figma Exercise",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
